###############################################################
#  Generated by:      Cadence Encounter 09.11-s084_1
#  OS:                Linux x86_64(Host ID ee215lnx03.ecn.purdue.edu)
#  Generated on:      Tue Mar  8 19:40:48 2016
#  Command:           floorPlan -r 2.0 0.6 50 50 50 50
###############################################################

Version: 8

Head Box: 0.0000 0.0000 2808.0000 4900.9500
IO Box: 300.0000 300.0000 2508.0000 4600.9500
Core Box: 350.4000 351.0000 2458.0500 4551.0000
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: core 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 core 350.4000 351.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_1 core 350.4000 381.0000 N 878 1 2.4000 0.0000
DefRow: ROW_2 core 350.4000 411.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_3 core 350.4000 441.0000 N 878 1 2.4000 0.0000
DefRow: ROW_4 core 350.4000 471.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_5 core 350.4000 501.0000 N 878 1 2.4000 0.0000
DefRow: ROW_6 core 350.4000 531.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_7 core 350.4000 561.0000 N 878 1 2.4000 0.0000
DefRow: ROW_8 core 350.4000 591.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_9 core 350.4000 621.0000 N 878 1 2.4000 0.0000
DefRow: ROW_10 core 350.4000 651.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_11 core 350.4000 681.0000 N 878 1 2.4000 0.0000
DefRow: ROW_12 core 350.4000 711.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_13 core 350.4000 741.0000 N 878 1 2.4000 0.0000
DefRow: ROW_14 core 350.4000 771.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_15 core 350.4000 801.0000 N 878 1 2.4000 0.0000
DefRow: ROW_16 core 350.4000 831.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_17 core 350.4000 861.0000 N 878 1 2.4000 0.0000
DefRow: ROW_18 core 350.4000 891.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_19 core 350.4000 921.0000 N 878 1 2.4000 0.0000
DefRow: ROW_20 core 350.4000 951.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_21 core 350.4000 981.0000 N 878 1 2.4000 0.0000
DefRow: ROW_22 core 350.4000 1011.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_23 core 350.4000 1041.0000 N 878 1 2.4000 0.0000
DefRow: ROW_24 core 350.4000 1071.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_25 core 350.4000 1101.0000 N 878 1 2.4000 0.0000
DefRow: ROW_26 core 350.4000 1131.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_27 core 350.4000 1161.0000 N 878 1 2.4000 0.0000
DefRow: ROW_28 core 350.4000 1191.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_29 core 350.4000 1221.0000 N 878 1 2.4000 0.0000
DefRow: ROW_30 core 350.4000 1251.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_31 core 350.4000 1281.0000 N 878 1 2.4000 0.0000
DefRow: ROW_32 core 350.4000 1311.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_33 core 350.4000 1341.0000 N 878 1 2.4000 0.0000
DefRow: ROW_34 core 350.4000 1371.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_35 core 350.4000 1401.0000 N 878 1 2.4000 0.0000
DefRow: ROW_36 core 350.4000 1431.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_37 core 350.4000 1461.0000 N 878 1 2.4000 0.0000
DefRow: ROW_38 core 350.4000 1491.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_39 core 350.4000 1521.0000 N 878 1 2.4000 0.0000
DefRow: ROW_40 core 350.4000 1551.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_41 core 350.4000 1581.0000 N 878 1 2.4000 0.0000
DefRow: ROW_42 core 350.4000 1611.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_43 core 350.4000 1641.0000 N 878 1 2.4000 0.0000
DefRow: ROW_44 core 350.4000 1671.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_45 core 350.4000 1701.0000 N 878 1 2.4000 0.0000
DefRow: ROW_46 core 350.4000 1731.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_47 core 350.4000 1761.0000 N 878 1 2.4000 0.0000
DefRow: ROW_48 core 350.4000 1791.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_49 core 350.4000 1821.0000 N 878 1 2.4000 0.0000
DefRow: ROW_50 core 350.4000 1851.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_51 core 350.4000 1881.0000 N 878 1 2.4000 0.0000
DefRow: ROW_52 core 350.4000 1911.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_53 core 350.4000 1941.0000 N 878 1 2.4000 0.0000
DefRow: ROW_54 core 350.4000 1971.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_55 core 350.4000 2001.0000 N 878 1 2.4000 0.0000
DefRow: ROW_56 core 350.4000 2031.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_57 core 350.4000 2061.0000 N 878 1 2.4000 0.0000
DefRow: ROW_58 core 350.4000 2091.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_59 core 350.4000 2121.0000 N 878 1 2.4000 0.0000
DefRow: ROW_60 core 350.4000 2151.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_61 core 350.4000 2181.0000 N 878 1 2.4000 0.0000
DefRow: ROW_62 core 350.4000 2211.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_63 core 350.4000 2241.0000 N 878 1 2.4000 0.0000
DefRow: ROW_64 core 350.4000 2271.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_65 core 350.4000 2301.0000 N 878 1 2.4000 0.0000
DefRow: ROW_66 core 350.4000 2331.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_67 core 350.4000 2361.0000 N 878 1 2.4000 0.0000
DefRow: ROW_68 core 350.4000 2391.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_69 core 350.4000 2421.0000 N 878 1 2.4000 0.0000
DefRow: ROW_70 core 350.4000 2451.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_71 core 350.4000 2481.0000 N 878 1 2.4000 0.0000
DefRow: ROW_72 core 350.4000 2511.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_73 core 350.4000 2541.0000 N 878 1 2.4000 0.0000
DefRow: ROW_74 core 350.4000 2571.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_75 core 350.4000 2601.0000 N 878 1 2.4000 0.0000
DefRow: ROW_76 core 350.4000 2631.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_77 core 350.4000 2661.0000 N 878 1 2.4000 0.0000
DefRow: ROW_78 core 350.4000 2691.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_79 core 350.4000 2721.0000 N 878 1 2.4000 0.0000
DefRow: ROW_80 core 350.4000 2751.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_81 core 350.4000 2781.0000 N 878 1 2.4000 0.0000
DefRow: ROW_82 core 350.4000 2811.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_83 core 350.4000 2841.0000 N 878 1 2.4000 0.0000
DefRow: ROW_84 core 350.4000 2871.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_85 core 350.4000 2901.0000 N 878 1 2.4000 0.0000
DefRow: ROW_86 core 350.4000 2931.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_87 core 350.4000 2961.0000 N 878 1 2.4000 0.0000
DefRow: ROW_88 core 350.4000 2991.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_89 core 350.4000 3021.0000 N 878 1 2.4000 0.0000
DefRow: ROW_90 core 350.4000 3051.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_91 core 350.4000 3081.0000 N 878 1 2.4000 0.0000
DefRow: ROW_92 core 350.4000 3111.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_93 core 350.4000 3141.0000 N 878 1 2.4000 0.0000
DefRow: ROW_94 core 350.4000 3171.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_95 core 350.4000 3201.0000 N 878 1 2.4000 0.0000
DefRow: ROW_96 core 350.4000 3231.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_97 core 350.4000 3261.0000 N 878 1 2.4000 0.0000
DefRow: ROW_98 core 350.4000 3291.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_99 core 350.4000 3321.0000 N 878 1 2.4000 0.0000
DefRow: ROW_100 core 350.4000 3351.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_101 core 350.4000 3381.0000 N 878 1 2.4000 0.0000
DefRow: ROW_102 core 350.4000 3411.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_103 core 350.4000 3441.0000 N 878 1 2.4000 0.0000
DefRow: ROW_104 core 350.4000 3471.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_105 core 350.4000 3501.0000 N 878 1 2.4000 0.0000
DefRow: ROW_106 core 350.4000 3531.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_107 core 350.4000 3561.0000 N 878 1 2.4000 0.0000
DefRow: ROW_108 core 350.4000 3591.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_109 core 350.4000 3621.0000 N 878 1 2.4000 0.0000
DefRow: ROW_110 core 350.4000 3651.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_111 core 350.4000 3681.0000 N 878 1 2.4000 0.0000
DefRow: ROW_112 core 350.4000 3711.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_113 core 350.4000 3741.0000 N 878 1 2.4000 0.0000
DefRow: ROW_114 core 350.4000 3771.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_115 core 350.4000 3801.0000 N 878 1 2.4000 0.0000
DefRow: ROW_116 core 350.4000 3831.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_117 core 350.4000 3861.0000 N 878 1 2.4000 0.0000
DefRow: ROW_118 core 350.4000 3891.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_119 core 350.4000 3921.0000 N 878 1 2.4000 0.0000
DefRow: ROW_120 core 350.4000 3951.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_121 core 350.4000 3981.0000 N 878 1 2.4000 0.0000
DefRow: ROW_122 core 350.4000 4011.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_123 core 350.4000 4041.0000 N 878 1 2.4000 0.0000
DefRow: ROW_124 core 350.4000 4071.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_125 core 350.4000 4101.0000 N 878 1 2.4000 0.0000
DefRow: ROW_126 core 350.4000 4131.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_127 core 350.4000 4161.0000 N 878 1 2.4000 0.0000
DefRow: ROW_128 core 350.4000 4191.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_129 core 350.4000 4221.0000 N 878 1 2.4000 0.0000
DefRow: ROW_130 core 350.4000 4251.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_131 core 350.4000 4281.0000 N 878 1 2.4000 0.0000
DefRow: ROW_132 core 350.4000 4311.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_133 core 350.4000 4341.0000 N 878 1 2.4000 0.0000
DefRow: ROW_134 core 350.4000 4371.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_135 core 350.4000 4401.0000 N 878 1 2.4000 0.0000
DefRow: ROW_136 core 350.4000 4431.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_137 core 350.4000 4461.0000 N 878 1 2.4000 0.0000
DefRow: ROW_138 core 350.4000 4491.0000 FS 878 1 2.4000 0.0000
DefRow: ROW_139 core 350.4000 4521.0000 N 878 1 2.4000 0.0000

######################################################
#  Track: dir start number space layer_num layer1 ...#
######################################################
Track: X 1.2000 1170 2.4000 1 3
Track: Y 1.5000 1634 3.0000 1 3
Track: Y 1.5000 1634 3.0000 1 2
Track: X 1.2000 1170 2.4000 1 2
Track: X 1.2000 1170 2.4000 1 1
Track: Y 1.5000 1634 3.0000 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: Y 4901.1000 1 25.6500
GCellGrid: Y 78.4500 124 39.0000
GCellGrid: Y -0.1500 2 39.6000
GCellGrid: X 78.1500 71 39.0000
GCellGrid: X -0.1500 2 39.3000

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: vdd -pwr
PhysicalNet: gnd -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
###########################################################################
#  <HierarchicalPartitions>                                               #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val isAltLayer=val isPffGroup=val > #
#         <Net name="net_name" /> ...                                     #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval coreToBottom=fval   #
#         pinSpacingNorth=val pinSpacingWest=val pinSpacingSouth=val      #
#         pinSpacingEast=val  blockedLayers=xval >       #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name"                    #
#                       pins=nr spacing=val isOptOrder=1 isAltLayer=1 >   #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num cell="name" >                       #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <Partition name="lab7_layout_design" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=2 pinSpacingWest=2 pinSpacingSouth=2 pinSpacingEast=2 blockedLayers=0x7 >
	<PinLayer side="N" Metal2=yes />
	<PinLayer side="W" Metal3=yes />
	<PinLayer side="S" Metal2=yes />
	<PinLayer side="E" Metal3=yes />
    </Partition>
</HierarchicalPartitions>

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################
Instance: nclk__L2_I7 MX 1344.0000 2091.0000
Instance: nclk__L2_I6 MX 1377.6000 2091.0000
Instance: nclk__L2_I5 MX 1411.2000 2091.0000
Instance: nclk__L2_I4 MX 1444.8000 2091.0000
Instance: nclk__L2_I3 MX 619.2000 2091.0000
Instance: nclk__L2_I2 MX 650.4000 2091.0000
Instance: nclk__L2_I1 MX 676.8000 2091.0000
Instance: nclk__L2_I0 MX 710.4000 2091.0000
Instance: nclk__L1_I0 MX 1044.0000 2091.0000
Instance: I0/LD/OCTRL/d_minus_reg_reg R0 2056.8000 1641.0000
Instance: I0/LD/OCTRL/d_plus_reg_reg R0 2052.0000 1881.0000
Instance: I0/LD/ENC/last_bit_reg R0 1908.0000 1881.0000
Instance: I0/LD/T_SR_0/curr_val_reg[7] R0 1404.0000 2421.0000
Instance: I0/LD/T_SR_0/curr_val_reg[6] MX 1476.0000 2091.0000
Instance: I0/LD/T_SR_0/curr_val_reg[5] MX 1404.0000 1911.0000
Instance: I0/LD/T_SR_0/curr_val_reg[4] R0 1392.0000 1641.0000
Instance: I0/LD/T_SR_0/curr_val_reg[3] R0 1540.8000 1881.0000
Instance: I0/LD/T_SR_0/curr_val_reg[2] MY 1764.0000 1881.0000
Instance: I0/LD/T_SR_0/curr_val_reg[1] MX 1677.6000 2091.0000
Instance: I0/LD/T_SR_0/curr_val_reg[0] R0 1776.0000 2421.0000
Instance: I0/LD/T_SR_1/curr_val_reg[7] R0 1322.4000 3621.0000
Instance: I0/LD/T_SR_1/curr_val_reg[6] R0 1396.8000 3021.0000
Instance: I0/LD/T_SR_1/curr_val_reg[5] MX 1281.6000 2811.0000
Instance: I0/LD/T_SR_1/curr_val_reg[4] MX 1552.8000 2811.0000
Instance: I0/LD/T_SR_1/curr_val_reg[3] MY 1660.8000 3261.0000
Instance: I0/LD/T_SR_1/curr_val_reg[2] R0 1526.4000 3621.0000
Instance: I0/LD/T_SR_1/curr_val_reg[1] R0 1663.2000 3621.0000
Instance: I0/LD/T_SR_1/curr_val_reg[0] R0 1788.0000 2601.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[0][7] R0 621.6000 4041.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[0][6] R0 525.6000 2421.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[0][5] MY 741.6000 1281.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[0][4] MX 621.6000 351.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[0][3] MX 1123.2000 351.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[0][2] MY 1272.0000 3021.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[0][1] R0 1192.8000 3741.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[0][0] R0 1202.4000 1521.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[1][7] R0 381.6000 3981.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[1][6] MX 350.4000 2811.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[1][5] R0 350.4000 1521.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[1][4] MX 352.8000 651.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[1][3] MX 873.6000 531.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[1][2] MX 873.6000 2991.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[1][1] R0 801.6000 3981.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[1][0] R0 852.0000 2301.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[2][7] MY 729.6000 3981.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[2][6] MY 729.6000 2421.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[2][5] MY 782.4000 1641.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[2][4] R180 770.4000 351.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[2][3] MX 1072.8000 531.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[2][2] R0 1084.8000 3021.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[2][1] MY 1272.0000 3741.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[2][0] MY 1288.8000 1641.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[3][7] MY 499.2000 3981.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[3][6] MX 427.2000 2991.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[3][5] R0 494.4000 1281.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[3][4] R180 494.4000 351.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[3][3] MX 904.8000 351.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[3][2] R0 873.6000 3021.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[3][1] R0 1012.8000 3981.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[3][0] R0 931.2000 2301.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[4][7] R0 590.4000 3981.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[4][6] R0 602.4000 3021.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[4][5] MY 607.2000 2301.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[4][4] R0 516.0000 921.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[4][3] R0 1065.6000 1281.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[4][2] MY 1310.4000 2601.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[4][1] MY 1173.6000 4041.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[4][0] MY 1315.2000 2301.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[5][7] MX 350.4000 2991.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[5][6] MX 470.4000 2091.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[5][5] MX 396.0000 2091.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[5][4] R0 396.0000 1281.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[5][3] R0 784.8000 861.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[5][2] R0 801.6000 2421.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[5][1] R0 784.8000 3381.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[5][0] R0 873.6000 1881.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[6][7] MY 652.8000 3741.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[6][6] R0 784.8000 3021.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[6][5] MX 758.4000 2091.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[6][4] MY 782.4000 921.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[6][3] R0 1164.0000 1161.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[6][2] MY 1180.8000 2421.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[6][1] MY 1152.0000 3621.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[6][0] MX 1118.4000 2091.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[7][7] R0 352.8000 3621.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[7][6] R0 352.8000 2421.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[7][5] R0 396.0000 1881.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[7][4] R0 374.4000 921.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[7][3] R0 892.8000 921.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[7][2] R0 902.4000 2421.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[7][1] R0 921.6000 3741.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UFIFORAM/fiforeg_reg[7][0] R0 1051.2000 1641.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/wrptr_r1_reg[3] R180 2188.8000 651.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/wrptr_r1_reg[2] R180 2200.8000 531.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/wrptr_r1_reg[1] MY 1526.4000 1161.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/wrptr_r1_reg[0] MY 1663.2000 1161.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/wrptr_r2_reg[3] R180 2052.0000 651.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/wrptr_r2_reg[2] R180 1910.4000 531.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/wrptr_r2_reg[1] R0 1504.8000 921.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/wrptr_r2_reg[0] R0 1646.4000 921.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/full_flag_r_reg R0 1540.8000 1641.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/waddr_reg[2] R180 1392.0000 651.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/waddr_reg[1] MY 1288.8000 1281.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/waddr_reg[0] MX 1123.2000 651.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/WPU1/binary_r_reg[0] MX 1202.4000 531.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/WPU1/binary_r_reg[1] R180 981.6000 351.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/WPU1/binary_r_reg[2] MX 1303.2000 351.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/WPU1/binary_r_reg[3] R180 1512.0000 351.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/WPU1/gray_r_reg[3] MX 1660.8000 351.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/WPU1/gray_r_reg[2] MX 1574.4000 531.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/WPU1/gray_r_reg[1] R0 1531.2000 1521.0000
Instance: I0/LD/T_FIFO/IP_FIFO/UWFC/WPU1/gray_r_reg[0] R0 1788.0000 861.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/rwptr_r1_reg[3] MX 1802.4000 351.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/rwptr_r1_reg[2] MX 1771.2000 531.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/rwptr_r1_reg[1] R0 1668.0000 1521.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/rwptr_r1_reg[0] R0 1800.0000 921.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/rwptr_r2_reg[3] R180 2052.0000 351.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/rwptr_r2_reg[2] MX 1785.6000 651.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/rwptr_r2_reg[1] R0 1776.0000 1641.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/rwptr_r2_reg[0] MY 1920.0000 1161.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/empty_flag_r_reg R0 2056.8000 921.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/raddr_reg[2] MY 1310.4000 921.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/raddr_reg[1] MY 1310.4000 1161.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/raddr_reg[0] MY 1389.6000 1521.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/RPU1/binary_r_reg[0] R0 2073.6000 1521.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/RPU1/binary_r_reg[1] R0 1814.4000 1521.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/RPU1/binary_r_reg[2] R0 2080.8000 1281.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/RPU1/binary_r_reg[3] R0 2181.6000 861.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/RPU1/gray_r_reg[3] MX 2059.2000 531.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/RPU1/gray_r_reg[2] MX 2188.8000 351.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/RPU1/gray_r_reg[1] R0 1526.4000 1281.0000
Instance: I0/LD/T_FIFO/IP_FIFO/URFC/RPU1/gray_r_reg[0] MY 1776.0000 1281.0000
Instance: I0/LD/TIM/curr_state_reg[0] MX 1785.6000 4251.0000
Instance: I0/LD/TIM/curr_state_reg[1] MY 1920.0000 4041.0000
Instance: I0/LD/TIM/clk_cnt_reg[0] R0 1396.8000 4041.0000
Instance: I0/LD/TIM/clk_cnt_reg[1] R0 1396.8000 3981.0000
Instance: I0/LD/TIM/clk_cnt_reg[2] MX 1526.4000 4251.0000
Instance: I0/LD/CTRL/bit_cnt_reg[0] R0 2052.0000 3981.0000
Instance: I0/LD/CTRL/bit_cnt_reg[1] MX 1920.0000 4251.0000
Instance: I0/LD/CTRL/bit_cnt_reg[2] R180 2181.6000 4251.0000
Instance: I0/LD/CTRL/curr_state_reg[0] R0 1800.0000 3021.0000
Instance: I0/LD/CTRL/curr_state_reg[2] MY 2181.6000 3741.0000
Instance: I0/LD/CTRL/curr_state_reg[1] R0 1785.6000 3381.0000
Instance: I0/LD/CTRL/curr_state_reg[3] R0 2025.6000 2301.0000

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

#################################################################
#  <PlacementBlockages>                                         #
#     <Blockage name="blk_name" type="hard|soft|partial">       #
#       <Attr density=1.2 inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </PlacementBlockages>                                        #
#################################################################

###########################################################################
#  <RouteBlockages>                                                       #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">   #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes />   #
#       <Layer type="route|cut|masterslice" id=layerNo />                 #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                       #
#     </Blockage>                                                         #
#  </RouteBlockages>                                                      #
###########################################################################

######################################################
#  PrerouteAsObstruct: <layer_treated_as_obstruct>   #
######################################################
PrerouteAsObstruct: 0x7

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: .lab7_layout_design10185.rs.fp.spr

#######################################################################################
#  IO: <instName> <cellName> <lx> <ly> <side> <orient> {-power|-ground|-} \           #
#      [isCovered isPrePlaced]                                                        #
#  IOPin: <pinName> <x> <y> <side> <layerId> <width> <depth> {placed|fixed|cover|-} <nrBox> #
#    PinBox: <llx> <lly> <urx> <ury>                                                  #
#    PinPoly: <nrPt> <x1> <y1> <x2> <y2> ...<xn> <yn>                                 #
#######################################################################################
IO: c401 PADFC 2508.0000 4600.9500 NE R270 - 01
IO: U308 PADNC 2299.0500 4600.9500 N R0 - 01
IO: U307 PADNC 2090.1000 4600.9500 N R0 - 01
IO: U306 PADNC 1881.1500 4600.9500 N R0 - 01
IO: U305 PADNC 1672.2000 4600.9500 N R0 - 01
IO: U304 PADNC 1463.4000 4600.9500 N R0 - 01
IO: U303 PADNC 1254.6000 4600.9500 N R0 - 01
IO: U302 PADNC 1045.8000 4600.9500 N R0 - 01
IO: U301 PADNC 836.8500 4600.9500 N R0 - 01
IO: U2 PADGND 627.9000 4600.9500 N R0 - 01
IO: U1 PADVDD 418.9500 4600.9500 N R0 - 01
IO: c402 PADFC 0.0000 4600.9500 NW R0 - 01
IO: U312 PADNC 0.0000 4201.6500 W R90 - 01
IO: U311 PADNC 0.0000 3802.5000 W R90 - 01
IO: U310 PADNC 0.0000 3403.3500 W R90 - 01
IO: U309 PADNC 0.0000 3004.2000 W R90 - 01
IO: U18 PADINC 0.0000 2605.0500 W R90 - 01
IO: U17 PADINC 0.0000 2205.9000 W R90 - 01
IO: U16 PADINC 0.0000 1806.7500 W R90 - 01
IO: U15 PADINC 0.0000 1407.6000 W R90 - 01
IO: U14 PADINC 0.0000 1008.4500 W R90 - 01
IO: U13 PADINC 0.0000 609.3000 W R90 - 01
IO: c403 PADFC 0.0000 0.0000 SW R90 - 01
IO: U321 PADNC 2299.0500 0.0000 S R180 - 01
IO: U320 PADNC 2090.1000 0.0000 S R180 - 01
IO: U319 PADNC 1881.1500 0.0000 S R180 - 01
IO: U318 PADNC 1672.2000 0.0000 S R180 - 01
IO: U317 PADNC 1463.4000 0.0000 S R180 - 01
IO: U316 PADNC 1254.6000 0.0000 S R180 - 01
IO: U315 PADNC 1045.8000 0.0000 S R180 - 01
IO: U314 PADNC 836.8500 0.0000 S R180 - 01
IO: U313 PADNC 627.9000 0.0000 S R180 - 01
IO: U7 PADINC 418.9500 0.0000 S R180 - 01
IO: c404 PADFC 2508.0000 0.0000 SE R180 - 01
IO: U300 PADNC 2508.0000 4201.6500 E R270 - 01
IO: U12 PADINC 2508.0000 3802.5000 E R270 - 01
IO: U11 PADINC 2508.0000 3403.3500 E R270 - 01
IO: U10 PADINC 2508.0000 3004.2000 E R270 - 01
IO: U9 PADINC 2508.0000 2605.0500 E R270 - 01
IO: U8 PADINC 2508.0000 2205.9000 E R270 - 01
IO: U6 PADOUT 2508.0000 1806.7500 E R270 - 01
IO: U5 PADOUT 2508.0000 1407.6000 E R270 - 01
IO: U4 PADOUT 2508.0000 1008.4500 E R270 - 01
IO: U3 PADOUT 2508.0000 609.3000 E R270 - 01

##########################################################################
#  <IOPins>                                                              #
#    <Pin name="pin_name" type="clock|power|ground|analog"               #
#         status="covered|fixed|placed" is_special=1 >                   #
#      <Port>                                                            #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d />             #
#        <Via name="via_name" x=1 y=2 /> ...                             #
#        <Layer id=id spacing=1.2 drw=1.2>                               #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                           #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />          #
#        </Layer> ...                                                    #
#      </Port>  ...                                                      #
#      <Antenna model=num type="name" value=float_num layer=num /> ...   #
#    </Pin> ...                                                          #
#  </IOPins>                                                             #
##########################################################################


#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="lab7_layout_design">
	<prop name="CUT_ROWS" type=Int value=0 />
	<prop name="optimization_trialRoute_guide_flow" type=Int value=1 />
  </Design>
</Properties>

###########################################################$############################################################################################
#  GlobalNetConnection: <net_name> {-pin|-inst|-net} <base_name_pattern> -type {pgpin|net|tiehi|tielo} {-all|-module <name>|-region <box>} [-override] #
########################################################################################################################################################
GlobalNetConnection: vdd -pin vdd -type pgpin -all
GlobalNetConnection: gnd -pin gnd -type pgpin -all
GlobalNetConnection: vdd -type tiehi -all
GlobalNetConnection: gnd -type tielo -all
GlobalNetConnection: vdd -pin vdd -type pgpin -all -override
GlobalNetConnection: gnd -pin gnd -type pgpin -all -override

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
